spring.application.name=NexBell

server.port=${PORT:8080}

spring.config.import=optional:file:./application-local.properties

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/nexora}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:false}

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.use-root-path=true
springdoc.swagger-ui.display-request-duration=true
springdoc.swagger-ui.try-it-out-enabled=true

authorization.jwt.secret=${AUTH_JWT_SECRET:nexorabackenddevsecretkeynexorabackenddevsecret}
authorization.jwt.expiration-milliseconds=${AUTH_JWT_EXPIRATION_MS:86400000}

nexbell.edge-service.host=localhost
nexbell.edge-service.port=3100

nexbell.edge-service.base-url=${NEXBELL_EDGE_BASE_URL:}
mqtt.broker.url=tcp://localhost:1883
mqtt.broker.username=nexbell-esp32
mqtt.broker.password=nexbell-mqtt-2026


firebase.credentials-path=${FIREBASE_CREDENTIALS_PATH:classpath:firebase-service-account.json}


nexbell.mail.enabled=${NEXBELL_MAIL_ENABLED:false}
nexbell.mail.from=${NEXBELL_MAIL_FROM:no-reply@nexbell.app}
sendgrid.api-key=${SENDGRID_API_KEY:}
